# Generated by Django 5.0.3 on 2024-04-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_users_options_alter_users_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='userName',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
    ]
