# Generated by Django 5.0.3 on 2024-04-03 16:25

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_username_users_name_alter_users_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='xiaoban_huzhen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4490)),
                ('dlmc', models.CharField(max_length=60, null=True, verbose_name='地类名称')),
                ('xiao_ban', models.CharField(max_length=5, null=True, verbose_name='小班代号')),
                ('lb_name', models.CharField(max_length=50, null=True, verbose_name='林班名')),
                ('di_ming', models.CharField(max_length=16, null=True, verbose_name='地名')),
                ('hai_ba', models.CharField(max_length=4, null=True, verbose_name='海拔')),
            ],
        ),
    ]
