# Generated by Django 5.0.3 on 2024-04-04 09:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_xiaoban_huzhen_dlbm_xiaoban_huzhen_xbmj'),
    ]

    operations = [
        migrations.CreateModel(
            name='yimu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4490)),
                ('lin_ban', models.CharField(max_length=4, null=True, verbose_name='林班')),
                ('xiao_ban', models.CharField(max_length=8, null=True, verbose_name='小班')),
                ('di_lei', models.CharField(max_length=4, null=True, verbose_name='地类')),
                ('cunname', models.CharField(max_length=50, null=True, verbose_name='村名')),
            ],
        ),
        migrations.AddField(
            model_name='xiaoban_huzhen',
            name='cun_name_1',
            field=models.CharField(max_length=50, null=True, verbose_name='村名'),
        ),
    ]
