# Generated by Django 5.0.3 on 2024-04-04 11:12

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_yimu_xiaoban_huzhen_cun_name_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yimu',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiLineStringField(null=True, srid=4490),
        ),
    ]
