# Generated by Django 5.0.3 on 2024-04-10 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_yimu_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='xiaoban_huzhen',
            name='lin_ban',
            field=models.CharField(max_length=4, null=True, verbose_name='林班'),
        ),
    ]
